### ISSUE TITLE
Uploaded image not rendering

### ISSUE THREAD

**Issue by evhan55** [OpenNewsLabs/guri-vr#50]
I dropped an image into the web editor and it created the following url:
https://gurivr.s3.amazonaws.com/e4aba193-288b-4a48-bbe2-b31bdac99446-rp7BPx.jpg

However, the following scene does not seem to render anything but black:
"Mi primera escena dura 10 segundos y tiene un panorama de https://gurivr.s3.amazonaws.com/e4aba193-288b-4a48-bbe2-b31bdac99446-rp7BPx.jpg"

Story:
https://s3.amazonaws.com/gurivr/s/f707e757aad7d9ca3ae11ca0.html

**Comment by impronunciable** [comment]
That was weird, I was calling "toLowerCase" on urls, it's fixed. You can try again at gurivr.com (worked for me)

Thanks again for reporting

**Comment by impronunciable** [comment]
(Try with a hard page refresh if not working inmediately "CMD + SHIFT + R")

**Comment by evhan55** [comment]
Great, gracias!  It works, how exciting! 💃
