### ISSUE TITLE
Spanish Guide

### ISSUE THREAD

**Issue by evhan55** [OpenNewsLabs/guri-vr#53]
I was wondering if the Spanish guide will have the possible keywords listed in Spanish somewhere?

For example, I'd like to know what the possible position keywords are in Spanish, but the Spanish guide says (with right,left,behind,front still in English):

> Texto
> 
> Podés escribir texto y va a ser ubicado dentro de la pantalla. No hay soporte de color ni texto por ahora.
> 
> Palabras clave: texto
> 
> Atributos:
> 
> text (string) | requerido
> position (right, left, behind, front) | opcional
> scale (tiny, small, large, huge) | opcional

Thanks!

**Comment by impronunciable** [comment]
It was just a laziness issue. Thanks for pointing it out. I'll fix it right away.

**Comment by impronunciable** [comment]
@evhan55 should be working now :) btw today I released in-editor search for images and panoramas :) https://twitter.com/guri_vr/status/780485522644987904

**Comment by evhan55** [comment]
Re: Guide in Spanish

Oh thanks! However I went to refresh (hard refresh) but the command keywords are still in English?

> Atributos:
> 
> text (string) | requerido
> position (right, left, behind, front) | opcional
> scale (tiny, small, large, huge) | opcional

Re: in-editor search

Oh my goodness!! That GIF is out of this world.  Back in 2009 I added in-editor search in Flickr for DesignBlocks, my Scratch/Processing hybrid project that I made back then.  All the features you envision are very near to my heart!  I cannot wait to test it all out!  I am currently writing a short blog post about my GuriVR experience so far, and I haven't even played with OBJ loading or anything!

**Comment by evhan55** [comment]
Great, I see the Spanish commands now!  Gracias!  Atras needed an accent, go figure! :)

And wow, speech recognition sounds great.  I saw in your Twitter feed a link to a program with speech commands for Spotify.  Just this morning, someone was asking me if it's possible to speak to Siri in Spanish, and I didn't know the answer!

**Comment by impronunciable** [comment]
Yeah! that's from one of the aframevr maintainers, it's pretty cool. Both the spotify demo and my implementation uses the web speech recognition API that supports multiple languages. At least on chrome for desktop I tried it on spanish and english both with good results (it's not amazing but much better than expected)

**Comment by evhan55** [comment]
I really can't wait to try it. That sounds super cool!

And thank you for alerting me to the fact that Flickr has panoramic searching.  I was having trouble finding freely available 360 panoramas, but I am having some luck there!

**Comment by impronunciable** [comment]
Oh yes, that group it's amazing! https://www.flickr.com/groups/equirectangular/

**Comment by evhan55** [comment]
Oh see I didn't even know the photos were called equirectangular, amazing.  I am learning so much from your project, thank you!!!
