### ISSUE TITLE
Remove the duration restriction

### ISSUE THREAD

**Issue by impronunciable** [OpenNewsLabs/guri-vr#57]
Most stories just have 1 scene and most of the times don't want to finish. If there is just one paragraph we can parse it anyway trying to find objects and make that chapter `static` meaning it never ends

**Comment by impronunciable** [comment]
removed :)

**Comment by impronunciable** [comment]
@evhan55 now you don't need to specify the duration anymore

**Comment by evhan55** [comment]
@impronunciable Oh, this is great!  Thank you for letting me know!  When I test it I will let you know.
