### ISSUE TITLE
demo not worked

### ISSUE THREAD

**Issue by jt3k** [OpenNewsLabs/guri-vr#67]
https://gurivr.com

**Comment by impronunciable** [comment]
@Which one?

**Comment by jt3k** [comment]
![2018-01-03 5 51 36](https://user-images.githubusercontent.com/1261240/34507736-2f81d1c2-f04a-11e7-97d0-2f539464c00a.png)
this one

**Comment by DayBr3ak** [comment]
https://gurivr.com is not working on chrome 67

**Comment by impronunciable** [comment]
Strange. It's working on my chrome 67 for mac. Can you give me more details on your environment @DayBr3ak?

thanks for reporting!

**Comment by jt3k** [comment]
ok. :rofl:  
![](https://i.imgur.com/gmnke9l.png)

**Comment by impronunciable** [comment]
haha thanks.  I´ll take a better look. I think I know whats happening. It has to do with locale, that's why I couldn't see it 👍

**Comment by jt3k** [comment]
just make the default locale = en )
