### ISSUE TITLE
Stories are not correctly saved when logged in

### ISSUE THREAD

**Issue by SilverChimerawing** [OpenNewsLabs/guri-vr#81]
I logged into Guri via magic email, went to My Stories > Add New Story and saved the demo story, then returned to My Stories. The story was displayed and its preview text was correct, but when I went to edit the story, I was presented with an empty console and nothing happened when I clicked the play button.
As a workaround for this, stories can be saved in text files and copy-pasted into the console for editing.

**Comment by impronunciable** [comment]
Thanks for reporting. I'll check this out

**Comment by impronunciable** [comment]
@SilverChimerawing It should be working. Let me know if it's not the case. Thanks again for reporting!
