### ISSUE TITLE
No puedo ver las panoramas...

### ISSUE THREAD

**Issue by robertoboote** [OpenNewsLabs/guri-vr#93]
Hola! estoy siguiendo las instrucciones que se sugieren y no logro ver una imagen en VR. Les paso el link de la misma:
https://vrguri.s3.sa-east-1.amazonaws.com/Camino2.jpg
Por favor, pueden decirme que estoy haciendo mal o que es lo que falta para poder hacer una VR. Muchas Gracias!

**Comment by impronunciable** [comment]
@robertoboote para que las imagenes funcionen hace falta que el servicio que las sirva tenga habilitado CORS (es un requerimiento más a bajo nivel). Lo que hice fue bajarla y volver a subirla a esta url que te va a servir https://firebasestorage.googleapis.com/v0/b/guri-dev.appspot.com/o/uploads%2F91cb2772-Camino2.jpeg?alt=media&token=fe57d660-d4f1-4d83-a5d1-cfe7ad534239

Si estás loggeado en gurivr podes arrastrar tus propias imagenes en el editor y se van a subir con los permisos necesarios.

saludos!
